### ISSUE TITLE
what are your thoughts about variable naming?

### ISSUE THREAD

**Issue by lamuria** [tostasqb/tracker#4]

**Comment by tostasqb** [comment]
Someone said one of the hardest things in coding is "naming variables". I kinda relate to that. 

I try to describe the use of the variable when naming it. A couple of years back I started using some [style guides](https://github.com/bbatsov/ruby-style-guide) to guide me better (linters too on atom like rubocop) and since then I left behind the beginning underscore trail. 

Anyhow, I don't usually begin my variables with the type intended to use like `str_name` or `int_phone`, I just use `name`, `address` or `items_per_page`. I like the snake_case (ruby) much better than the capitalLetter (js) practice, but I use both correspondently.
